---
- name: Install and configure Wordpress
  hosts: localhost

  tasks:
  # - name: Install ssm-agent
  #   command: sudo yum install -y https://s3.ap-southeast-2.amazonaws.com/amazon-ssm-ap-southeast-2/latest/linux_amd64/amazon-ssm-agent.rpm
  
  # - name: Restart amazon-ssm-agent
  #   service:
  #     name: amazon-ssm-agent
  #     state: restarted

  
  - name: Install php and mariadb
    command: amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2

  - name: Install httpd
    yum:
      name: httpd
      state: latest
  
  - name: Enable httpd service
    service:
      name: httpd
      enabled: yes

  - name: Restart httpd
    service:
      name: httpd
      state: restarted

  - name: Download and Unarchive Wordpress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/
      remote_src: "yes"

  - name: Remove httpd default
    file:
      path: /var/www/html
      state: absent

  - name: Copy wp-config
    template:
      src: wp-config.php.j2
      dest: /var/www/wordpress/wp-config.php
    vars:
      db_host: {{db_host}}
      db_name: {{db_name}}
      db_user: {{db_user}}
      db_password: {{db_password}}