version: 2.1

jobs:
  terraform-plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd terraform/network
            terraform init -input=false
            terraform plan -out tfapply -var-file environment.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform-apply
          command: |
            cd terraform/network
            terraform apply -auto-approve tfapply
            echo 'export VPC_ID=`terraform output vpc_id`' >> $BASH_ENV
            echo 'export PUBLIC_SUBNET_ID=`terraform output public_subnet_id`' >> $BASH_ENV
      - persist_to_workspace:
          root: .
          paths:
            - .

  packer-validate:
    docker:
      - image: hashicorp/packer:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: packer-validate
          command: |
            cd packer
            packer validate packer.json
      - persist_to_workspace:
          root: .
          paths:
            - .

  packer-build:
    docker:
      - image: hashicorp/packer:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: packer-build
          command: |
            cd packer
            packer build -var subnet_id=${PUBLIC_SUBNET_ID} packer.json
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-plan-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            cd terraform/network
            terraform plan -destroy -out tfdestroy -var-file environment.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            cd terraform/network
            terraform apply -auto-approve tfdestroy

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - terraform-plan-apply
      - terraform-hold-apply:
          type: approval
          requires:
            - terraform-plan-apply
      - terraform-apply:
          requires:
            - terraform-hold-apply
      - packer-hold:
          type: approval
          requires:
            - terraform-apply
      - packer-validate:
          requires:
            - packer-hold
      - packer-build:
          requires:
            - packer-validate
      - terraform-plan-destroy:
          requires:
            - packer-build
      - terraform-hold-destroy:
          type: approval
          requires:
            - terraform-plan-destroy
      - terraform-destroy:
          requires:
            - terraform-hold-destroy