version: 2

orbs:
  packer: salaxander/packer@0.1

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd terraform/network
            terraform init -input=false
            terraform plan -out tfapply -var-file environment.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd terraform/network
            terraform apply -auto-approve tfapply
            echo 'export VPC_ID=`terraform output vpc_id`' >> $BASH_ENV
            echo 'export PUBLIC_SUBNET_ID=`terraform output public_subnet_id`' >> $BASH_ENV
      - persist_to_workspace:
          root: .
          paths:
            - .

  packer:
    executor: packer/default
    steps:
      - checkout
      - build:
          template: /packer/packer.json
          args: |
            -var aws_region=ap-southeast-2
            -var vpc_id=${VPC_ID}
            -var subnet_id=${PUBLIC_SUBNET_ID}
            -var branch=${CIRCLE_BRANCH}

  plan-destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            cd terraform/network
            terraform plan -destroy -out tfdestroy -var-file environment.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            cd terraform/network
            terraform apply -auto-approve tfdestroy

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - hold-packer:
          type: approval
          requires:
            - apply
      - packer:
          requires:
            - hold-packer
      - plan-destroy:
          requires:
            - packer
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy