db_prefix         = "wordpress-mysql"
db_instance_class = "db.t3.micro"
db_name           = "wordpress"
db_user           = "{db_user}"
db_password       = "{db_password}"
db_engine         = "mysql"
db_version        = "8.0.21"
db_storage        = "gp2"
